site_name: Documentação de Análise

theme:
  name: material
  language: pt-BR
  features:
    - navigation.path
    - navigation.indexes

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - attr_list
  - md_in_html

